### ISSUE TITLE
Support report_paths

### ISSUE THREAD

**Issue by dcramer** [codecov/basic-test-results#11]
Allow multiple locations using grep-style search:

```yaml
      - name: Publish Test Report
        uses: codecov/basic-test-results@v1
        if: ${{ !cancelled() }}
        with:
          report_paths: "**/*.junit.xml"
```
